# Generated by Django 5.2.2 on 2025-06-12 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Learner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name_ar', models.CharField(max_length=30, verbose_name='الاسم الأول (ع)')),
                ('last_name_ar', models.CharField(max_length=30, verbose_name='اسم العائلة (ع)')),
                ('first_name_en', models.CharField(max_length=30, verbose_name='First Name (En)')),
                ('last_name_en', models.CharField(max_length=30, verbose_name='Last Name (En)')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
