# Generated by Django 5.2.2 on 2025-06-13 13:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='learner',
            name='department',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='الإدارة'),
        ),
        migrations.AddField(
            model_name='learner',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='البريد الإلكتروني'),
        ),
        migrations.AddField(
            model_name='learner',
            name='employee_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='الرقم الوظيفي'),
        ),
        migrations.AddField(
            model_name='learner',
            name='manager',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='المدير المباشر'),
        ),
        migrations.AddField(
            model_name='learner',
            name='mobile',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='رقم الجوال'),
        ),
        migrations.AddField(
            model_name='learner',
            name='national_id',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='رقم الهوية'),
        ),
        migrations.AddField(
            model_name='learner',
            name='nationality',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='الجنسية'),
        ),
        migrations.AddField(
            model_name='learner',
            name='section',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='القسم'),
        ),
        migrations.AddField(
            model_name='learner',
            name='sector',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='القطاع'),
        ),
        migrations.AddField(
            model_name='learner',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
