# Generated by Django 5.2.2 on 2025-06-16 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_reference_tables_and_timestamps'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='learner',
            options={'verbose_name': 'متدرّب', 'verbose_name_plural': 'المتدرّبون'},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'verbose_name': 'القسم', 'verbose_name_plural': 'الأقسام'},
        ),
    ]
