# Generated by Django 5.2.2 on 2025-06-18 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_recruitmentemployee_employeeevaluation'),
        ('core', '0010_add_is_haramain'),
    ]

    operations = [
    ]
