# Generated by Django 5.2.2 on 2025-06-18 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_merge_20250618_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeevaluation',
            name='is_haramain',
            field=models.BooleanField(default=False, verbose_name='حرمين'),
        ),
        migrations.AddField(
            model_name='recruitmentemployee',
            name='is_haramain',
            field=models.BooleanField(default=False, verbose_name='حرمين'),
        ),
    ]
