# Generated by Django 5.2.2 on 2025-06-18 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_add_final_score'),
        ('core', '0012_employeeevaluation_is_haramain_and_more'),
    ]

    operations = [
    ]
