# Generated by Django 5.2.2 on 2025-06-18 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_update_recruitmentemployee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruitmentemployee',
            name='name',
            field=models.CharField(max_length=100, verbose_name='الاسم عربي'),
        ),
    ]
