# Generated by Django 5.2.2 on 2025-06-20 18:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_recruitmentemployee_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecruitmentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255, verbose_name='اسم الملف')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الرفع')),
                ('report_date', models.DateField(verbose_name='تاريخ الكشف')),
                ('columns', models.JSONField(verbose_name='الأعمدة')),
                ('rows', models.JSONField(verbose_name='الصفوف')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='تم الرفع بواسطة')),
            ],
            options={
                'verbose_name': 'كشف استقدام',
                'verbose_name_plural': 'كشوف الاستقدام',
                'unique_together': {('filename', 'report_date')},
            },
        ),
    ]
