# Generated by Django 5.2.2 on 2025-06-20 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_recruitmentreport_is_haramain'),
        ('core', '0016_recruitmentreport'),
    ]

    operations = [
    ]
