# Generated by Django 5.2.2 on 2025-07-11 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_legacyrecruitmentrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legacyrecruitmentrecord',
            name='date',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='legacyrecruitmentrecord',
            name='emp_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Emp. ID'),
        ),
        migrations.AlterField(
            model_name='legacyrecruitmentrecord',
            name='employees',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Employees'),
        ),
        migrations.AlterField(
            model_name='legacyrecruitmentrecord',
            name='evaluation',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Evaluation'),
        ),
        migrations.AlterField(
            model_name='legacyrecruitmentrecord',
            name='month_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Month Number'),
        ),
        migrations.AlterField(
            model_name='legacyrecruitmentrecord',
            name='year',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Year'),
        ),
    ]
